### ISSUE TITLE
Does it use eval under the hood?

### ISSUE THREAD

**Issue by cozimacode** [marten-de-vries/evaljs#55]
Hi there,

Does this use `eval()` under the hood? If not, do we have any security concerns (XSS or injections) to be aware of?

Thank you

**Comment by adjenks** [comment]
The whole point of using this is to be able to "eval" code when the `eval()` function itself is blocked by the environment. So it wouldn't make any sense for it to use `eval()`. That would break its purpose. Using this would be just as dangerous as using eval, but likely much slower.

**Comment by cozimacode** [comment]
> The whole point of using this is to be able to "eval" code when the `eval()` function itself is blocked by the environment. So it wouldn't make any sense for it to use `eval()`. That would break its purpose. Using this would be just as dangerous as using eval, but likely much slower.

Thank you for clarifying this, @adjenks. I was looking for a solution which doesn't use eval. JShint unfortunately doesn't serve my entire purpose. Probably have to research how the web editors accept user code and handle security concerns :)

**Comment by adjenks** [comment]
@cozimacode If you want to allow users to execute javascript, it's a very tricky subject and is best handled by hosting and running the JavasScript on a separate domain and locking down the Content Security Policies. You can then display the results using `<iframe/>`s with safe Content Security Policies that prevent the iframe from accessing your other domains at all. Basically create an environment where it's "safe" for a user to run any malicious code by isolating their code on a separate server on a separate domain. Ship their code to that domain and run it in an iframe.

**Comment by cozimacode** [comment]
@adjenks Interesting. What do you think about using it inside a web worker? Workers don't have access to DOM and we can disable http requests as well I believe.

**Comment by adjenks** [comment]
@cozimacode 
I haven't explored that. Sounds promising but I'm not familiar. Scenarios I've explored required access to DOM.
Let me know how your project goes.
